// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsnGxkwCO9sZn8SEfmufM5VoEC96-S4FY',
    appId: '1:113404389798:web:ec29201399bd9332878767',
    messagingSenderId: '113404389798',
    projectId: 'fir-demo-cd1d6',
    authDomain: 'fir-demo-cd1d6.firebaseapp.com',
    storageBucket: 'fir-demo-cd1d6.appspot.com',
    measurementId: 'G-XST4DF91EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwLBQCs_yIXUkaVrND6wkLQRGB2_rZWuw',
    appId: '1:113404389798:android:b4cc6d3e2bcd322f878767',
    messagingSenderId: '113404389798',
    projectId: 'fir-demo-cd1d6',
    storageBucket: 'fir-demo-cd1d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4dczlqaNi9veacptdSGqxo2kj5HdgXSE',
    appId: '1:113404389798:ios:8002a7a9b94f7882878767',
    messagingSenderId: '113404389798',
    projectId: 'fir-demo-cd1d6',
    storageBucket: 'fir-demo-cd1d6.appspot.com',
    iosClientId: '113404389798-k6qhmphki93d6acsm0gb11hr0djhrmso.apps.googleusercontent.com',
    iosBundleId: 'com.example.firStorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4dczlqaNi9veacptdSGqxo2kj5HdgXSE',
    appId: '1:113404389798:ios:8002a7a9b94f7882878767',
    messagingSenderId: '113404389798',
    projectId: 'fir-demo-cd1d6',
    storageBucket: 'fir-demo-cd1d6.appspot.com',
    iosClientId: '113404389798-k6qhmphki93d6acsm0gb11hr0djhrmso.apps.googleusercontent.com',
    iosBundleId: 'com.example.firStorage',
  );
}
